### ISSUE TITLE
Installing form helm chart I can't assign a manually created PVC for trow

### ISSUE THREAD

**Issue by chromafunk** [Trow-Registry/trow#366]
How I'm supposed to give this chart a PVC that already exists and it's bound to a PV ? 
```
volumeClaim:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
```

I have tried many ways of doing it but none work, thanks
